[package]

name = "mio"
version = "0.0.1"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies.nix]

git = "https://github.com/reem/nix-rust"

[dependencies.time]

git = "https://github.com/reem/time"

[[test]]

name = "test"
path = "test/test.rs"
